# Generated by Django 3.0.6 on 2020-10-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeHouse', '0005_auto_20201022_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='map',
        ),
        migrations.AddField(
            model_name='company_details',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='company_details',
            name='longitude',
            field=models.FloatField(null=True),
        ),
    ]
