# Generated by Django 3.0.6 on 2020-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafeHouse', '0006_auto_20201022_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('subject', models.TextField(max_length=200, null=True)),
                ('message', models.TextField(max_length=500, null=True)),
            ],
        ),
    ]
